version: "3"

services:
  # db:
  #   image: mysql
  #   restart: always
  #   container_name: sowlmate-db
  #   environment:
  #     - MYSQL_ROOT_HOST='%'
  #     - MYSQL_ROOT_PASSWORD=SoWl@#MaTe1298
  #     - MYSQL_USER=sowlmate
  #     - MYSQL_PASSWORD=SoWl@#MaTe1298
  #     - MYSQL_DATABASE=sowlmate
  #   ports:
  #     - 3307:3306
  #   networks:
  #     - backdb

  back:
    build:
      context: ./sowlmate
      dockerfile: Dockerfile
      # target: finalApp
    image: sowlmate308/sowlmate:back
    container_name: sowlmate-back
    restart: always
    ports:
      - 8080:8080
    # depends_on:
    #   - db
    # networks:
    #   - backdb

  kurento:
    build: ./kurento
    image: sowlmate308/sowlmate:kurento
    container_name: sowlmate-kurento
    restart: always
    ports:
      - 8443:8443
    depends_on:
      - back

  front:
    build: ./front
    image: sowlmate308/sowlmate:front
    container_name: sowlmate-front
    restart: always
    ports:
      - 80:80
    depends_on:
      - kurento
    # networks:
    #   - frontback
# networks:
#   backdb:
#     driver: bridge
#   frontback:
#     driver: bridge
