server:
  port: 8080
  servlet:
    context-path: /api/v1
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: SoWl@#MaTe1298
    key-store-type: PKCS12
    enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.38.245.51:3306/sowlmate?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: sowlmate
    password: SoWl@#MaTe1298

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

# find password by email
  mail:
    host: smtp.gmail.com
    port: 587
    username: sowlmate308@gmail.com
    password: junzjoauzkudlmkn
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
#      mail.smtp.ssl.enable: true

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 710793534732-kgcut5qhk7kab496eh1i8k8pkcsaoje5.apps.googleusercontent.com
#            #            client-id: 710793534732-kgcut5qhk7kab496eh1i8k8pkcsaoje5.apps.googleusercontent.com
#            clientSecret: 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
#            scope:
#              - email
#              - profile

#  profiles:
#    include: google
#  profiles:
#    include: API-KEY

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.ssafy.sowlmate: debug

springdoc:
  version: v0.0.1
  api-docs:
    path: /api-docs
    version: openapi_3_0
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /users/**
